### ISSUE TITLE
generating javadoc fails

### ISSUE THREAD

**Issue by ghost** [MrcJkb/module-finder#5]
I have a gradle java library project.
if I add your plugin without generating javadoc, I am able to run `./gradlew clean publishToMavenLocal` but if I add configuration to generate javadoc, I get the same errors as when I don't add your plugin.

configuration with errors when running `./gradlew clean publishToMavenLocal` :
```groovy
plugins {
    id 'java-library'
    id 'maven-publish'
    id "com.github.mrcjkb.module-finder" version "0.0.6"
}

group = 'net.nlacombe'
version = '1.0.0'

dependencies {
    // dependencies that I am omitting here, some of them I want to include as automatic modules
}

repositories {
    mavenCentral()
    mavenLocal()
}

task javadocJar(type: Javadoc) {
	source = sourceSets.main.allJava
	options.quiet()
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
    modularity.inferModulePath = true

    withJavadocJar()
    withSourcesJar()
}

publishing {
    publications {
        libraryName(MavenPublication) {
            from components.java
        }
    }
}

wrapper {
    gradleVersion = '6.8.3'
}
```

configuration with **no** errors when running `./gradlew clean publishToMavenLocal` :
```groovy
plugins {
    id 'java-library'
    id 'maven-publish'
    id "com.github.mrcjkb.module-finder" version "0.0.6"
}

group = 'net.nlacombe'
version = '1.0.0'

dependencies {
    // dependencies that I am omitting here, some of them I want to include as automatic modules
}

repositories {
    mavenCentral()
    mavenLocal()
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
    modularity.inferModulePath = true

    withJavadocJar()
    withSourcesJar()
}

publishing {
    publications {
        libraryName(MavenPublication) {
            from components.java
        }
    }
}

wrapper {
    gradleVersion = '6.8.3'
}
```

the only difference between the 2 is the following code: 
```groovy
task javadocJar(type: Javadoc) {
	source = sourceSets.main.allJava
	options.quiet()
}
```

my guess is that you modify the name of the source set that my custom javadoc task should use, but even after skiiming your code I did not see any obvious name I should use for the source set

oh and btw, thanks a lot for this gradle plugin! it will be super useful for me since it will allow me to migrate most of my project to jpms. which will add more validation that my libs and apps don't depende on transitive dependenice that are not declared as direcdt dependencies 🙂

**Comment by ghost** [comment]
actually, I am getting that error even without using your gradle plugin on another project, so I will close this issue.
most likely my javadocJar task configuration no longer works with gradle jpms changes

**Comment by mrcjkb** [comment]
Hi.

Have you recently changed JDKs during your project migration?
Some older projects may cause Javadoc linting to fail on newer JDKs.

You can either disable linting in your `JavadocJar` task: `options.addStringOption('Xdoclint:none', '-quiet')`

Or you can go through the error messages and warnings and adjust your Javadoc accordingly.

Best,
Marc

**Comment by ghost** [comment]
> Have you recently changed JDKs during your project migration?
> Some older projects may cause Javadoc linting to fail on newer JDKs.

yes, but I looked quickly and I think I have re-built all dependent projects with the same jdk.

> You can either disable linting in your JavadocJar task: options.addStringOption('Xdoclint:none', '-quiet')

afaik that is what `options.quiet()` does, also even if I remove that line, the build still fails
ex: this fails:
```groovy
task javadocJar(type: Javadoc) {
	source = sourceSets.main.allJava
}
```

> Or you can go through the error messages and warnings and adjust your Javadoc accordingly.

this is a library only used by myself (anc created by myself).
I want to be able to add javadoc to some specific places and having the javadoc generated for where this library is consumed, but I don't want to add javadoc to all public members.
the javadoc linting gives me warnings for every public member that does not have javadoc.

this is not critically important though since I am the only consumer.
so I will just turn off javadoc generation and just generate the sources jar.
that way I can look at the sources' javadoc when I want to remember the contract I had created in the library for a particularly ambiguous peice of code.

**Comment by mrcjkb** [comment]
The `quiet()` option only suppresses output of warnings. It doesn't disable linting.

But I doubt it's the warnings that are causing the task to fail.

Best,
Marc
